import { Anonymous_Pro } from 'next/font/google'
import '../styles/global.css'

import { Layout } from '@/components/shared/Layout/Layout.shared'

import type { Metadata } from 'next'

const anonPro = Anonymous_Pro({ subsets: ['cyrillic', 'latin'], weight: ['400', '700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ru'>
      <body className={anonPro.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  )
}
